## Smart Bridge Externship program in Applied Data Science
### Assignment-1
by Yashvardhan Singh (20BAI10135)
\<yashvardhan.singh2020@vitbhopal.ac.in\>

1. Assign your Name to variable `name` and Age to variable `age`. Make a Python program that prints your `name` and `age`.

In [1]:
name = 'Yashvardhan Singh'
age = 20
print('name:', name, 'age:', age)

name: Yashvardhan Singh age: 20


2. `X = "Datascience is used to extract meaningful insights."` Split the string


In [2]:
x = "Datascience is used to extract meaningful insights."
splitted = x.split()
print(splitted)

['Datascience', 'is', 'used', 'to', 'extract', 'meaningful', 'insights.']


3. Make a function that gives multiplication of two numbers


In [4]:
def multiply (a, b):
  return a * b
print(multiply(2, 3))

6


4. Create a Dictionary of 5 States with their capitals. Also print the keys and values.


In [5]:
geo = {'Uttar Pradesh': 'Lucknow', 'Madhya Pradesh': 'Bhopal', 'Kerala': 'Thiruvananthapuram', 'Tamil Nadu': 'Chennai', 'Assam': 'Dispur'}
print(geo.keys())
print(geo.values())

dict_keys(['Uttar Pradesh', 'Madhya Pradesh', 'Kerala', 'Tamil Nadu', 'Assam'])
dict_values(['Lucknow', 'Bhopal', 'Thiruvananthapuram', 'Chennai', 'Dispur'])


5. Create a list of 1000 numbers using range function.

In [7]:
bigList = [i for i in range(1, int(1e3+1))]
print(bigList)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 22

6. Create an identity matrix of dimension 4 by 4

In [9]:
import numpy as np
I = np.identity(4, dtype=int)
print(I)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


7. Create a 3x3 matrix with values ranging from 1 to 9

In [13]:
matrix_3_3 = [[j for j in range(i, i + 3)] for i in range(1, 9, 3)]
matrix_3_3 = np.array(matrix_3_3)
print(matrix_3_3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


8. Create 2 similar dimensional array and perform sum on them.

In [15]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(a + b)

[[ 6  8]
 [10 12]]


9. Generate the series of dates from 1st Feb, 2023 to 1st March, 2023 (both inclusive)

In [19]:
import pandas as pd 
times = pd.date_range(start='2023-02-01', end='2023-03-01', freq='1D')
for day in times:
  print(day, end=' | ')

2023-02-01 00:00:00 | 2023-02-02 00:00:00 | 2023-02-03 00:00:00 | 2023-02-04 00:00:00 | 2023-02-05 00:00:00 | 2023-02-06 00:00:00 | 2023-02-07 00:00:00 | 2023-02-08 00:00:00 | 2023-02-09 00:00:00 | 2023-02-10 00:00:00 | 2023-02-11 00:00:00 | 2023-02-12 00:00:00 | 2023-02-13 00:00:00 | 2023-02-14 00:00:00 | 2023-02-15 00:00:00 | 2023-02-16 00:00:00 | 2023-02-17 00:00:00 | 2023-02-18 00:00:00 | 2023-02-19 00:00:00 | 2023-02-20 00:00:00 | 2023-02-21 00:00:00 | 2023-02-22 00:00:00 | 2023-02-23 00:00:00 | 2023-02-24 00:00:00 | 2023-02-25 00:00:00 | 2023-02-26 00:00:00 | 2023-02-27 00:00:00 | 2023-02-28 00:00:00 | 2023-03-01 00:00:00 | 

10. Given a dictionary, convert it into corresponding dataframe and display it
```python
dictionary = {'Brand': ['Maruti', 'Renault', 'Hyndai'], 'Sales' : [250, 200, 240]}
```

In [24]:
data = {'Brand':['Maruti', 'Renault', 'Hyndai'], 'Sales':[250, 200, 240]}
df = pd.DataFrame.from_dict(data=data)
print(df.head())

     Brand  Sales
0   Maruti    250
1  Renault    200
2   Hyndai    240
